example: 'fireeye'

### Data path
train_data_path: '../data/all_file/'                    # Training data
train_label_path: '../data/train_data_label.csv' # Training label
valid_data_path: '../data/all_file/'                    # Validation Data
valid_label_path: '../data/val_data_label.csv' # Validation Label



### output path
log_dir: '../log/'
pred_dir: '../pred/'
checkpoint_dir: '../checkpoint/'

### Parameter
use_gpu: True             #
use_cpu: 1                # Number of cores to use for data loader
display_step: 20           # Std output update rate during training
test_step: 20             # Test per n step
lr: 0.0001     #
epochs: 50            # Number of steps to train
batch_size: 32            #
first_n_byte: 102400     # First N bytes of a PE file as the input of MalConv (defualt: 2 million)
window_size: 512          # Kernel size & stride for fireeye
sample_cnt: 1             # Number of data sampled for trianing (defualt 1 = all)